### PR TITLE
main window will now pop up on linux

### PR DESCRIPTION
**Pull request by scopatz**
I don't know if this is helpful, but the main cycic window wasn't displaying on linux until I implemented this.  Also, the Separations form seems to work just fine with the schema as implemented in cyclus/cyclus#1143.  I hope this helps.

### CODE REVIEW

**Comment by FlanFlanagan** [comment]
It is still broken on windows builds. Or just for me. You might be using an updated schema compared to me?

**Comment by scopatz** [comment]
I am using my 's' branch for both cyclus and cycamore.  The breakage was in the :cycamore:Reactor, for what it is worth.

**Comment by FlanFlanagan** [comment]
Not what I'm seeing, still broken in separations.

**Comment by scopatz** [comment]
What is the error?

**Comment by FlanFlanagan** [comment]
There is no error, it stops at the separations facility. My console just stops working. Would you mind giving me a cyclus -m from your machine?

**Comment by scopatz** [comment]
Sure, just emailed it to you.

**Comment by FlanFlanagan** [comment]
The reactor is working fine for me, separations is broken still.

**Comment by scopatz** [comment]
Is your github remote master up-to-date?  I just double checked from your current master and a clean build and it works just fine on Linux.

**Comment by scopatz** [comment]
Here is a screenshot

sep

**Comment by FlanFlanagan** [comment]
I mean that's right. But it's not working on Windows. Your reactor is broken?

**Comment by scopatz** [comment]
I'll rebuild cycamore to try to find out.

**Comment by scopatz** [comment]
after a merge from master that is.

**Comment by FlanFlanagan** [comment]
My reactor looks like this. 
rx

**Comment by FlanFlanagan** [comment]
Great Success.

image

However, annotations are still broken in this case.

**Comment by scopatz** [comment]
I just rebuilt everything from scratch, having updated cyclus and cycamore from the v1.3.0-release branch, merged with the s branches, and a clean built of cyclist and a press of the "Discover Archetypes" button, and here is what I see for the reactor:

rx

**Comment by scopatz** [comment]
Woohoo!

> However, annotations are still broken in this case

What do you mean by annotations?  Isn't all of this data part of the annotations?

**Comment by FlanFlanagan** [comment]
"commods" I believe has a uitype of "outcommodity" and should therefore be a drop down menu. This is not displaying.

**Comment by scopatz** [comment]
You are right, it does and should

**Comment by FlanFlanagan** [comment]
The form building as is, is simply because I modified to the schema reader to build even if the annotations failed. This means CycIC should always build, but will not always show the annotations. I'm trying to fix that now.

**Comment by scopatz** [comment]
Is the structure being inferred from the type, the alias, or the uitype?

**Comment by FlanFlanagan** [comment]
It should be from the uitype. If it doesn't see a uitype it takes the type (which comes directly from the schema)

**Comment by scopatz** [comment]
OK great!

**Comment by scopatz** [comment]
Ok.  I am pretty sure that this is an issue in combiner() and the fact that outcommodity is being assigned to the item rather than the commod.

**Comment by FlanFlanagan** [comment]
Yeah, I'm already trying to fix this. It looks like I need to rewrite the infoControl functions.

**Comment by scopatz** [comment]
Well, there just needs to be a clause somewhere that skips the first
nesting level inside of a map.  I didn't see any of these functions that
leveraged the type info explicitly, though I could be missing this.

**Comment by FlanFlanagan** [comment]
Yes. I'm aware. It was not required until this recent change, hence the working on it now.

**Comment by scopatz** [comment]
Ho-kay.  Just making sure I am on the same page as you.

**Pull request merged**
