### PR TITLE
cat now uses json array tostring method

### PR DESCRIPTION
**Pull request by gidden**
look at me! I'm a java developer =).

### CODE REVIEW

**Comment by FlanFlanagan** [comment]
Unfortunately it is not this easy. You can't convert a jsonArray to a string like that. You'll need to go through each item in the jsonArray and add them to a new ArrayList<String>, which you'll then need to add to the facArray using facArray.sey(4, tempArray). 

Or conversely you could create a new string out of the objects in that array and add them to each other with commas in between.

**Comment by gidden** [comment]
are you sure? here's an example where it looks to be doing something very similar:
https://code.google.com/p/json-simple/wiki/EncodingExamples#Example_2-2_-_Encode_a_JSON_array_-_Streaming

**Comment by gidden** [comment]
are you worried about the brackets pre- and post-pending the string?

**Comment by FlanFlanagan** [comment]
If the mainview loaded with that change then it's fine, that's surprising
though.

If you could remove the brackets that'd be nice. Currently CycIC looks for
a string like this.

"something1, something2, something3"

Then splits on the comma and uses the resulting vector to populate the
combo box.

On Wed, May 20, 2015 at 11:44 AM, Matthew Gidden <notifications@github.com>
wrote:

> are you worried about the brackets pre- and post-pending the string?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FlanFlanagan/cyclist2/pull/10#issuecomment-103955168>.
>



-- 
Robert Flanagan
Graduate Research Assistant
Nuclear and Radiation Engineering Program
Department of Mechanical Engineering
The University of Texas at Austin

**Comment by gidden** [comment]
done.

just FYI, I'm loading up the mainview as my test.

On Wed, May 20, 2015 at 11:49 AM, FlanFlanagan <notifications@github.com>
wrote:

> If the mainview loaded with that change then it's fine, that's surprising
> though.
>
> If you could remove the brackets that'd be nice. Currently CycIC looks for
> a string like this.
>
> "something1, something2, something3"
>
> Then splits on the comma and uses the resulting vector to populate the
> combo box.
>
> On Wed, May 20, 2015 at 11:44 AM, Matthew Gidden <notifications@github.com
> >
> wrote:
>
> > are you worried about the brackets pre- and post-pending the string?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/FlanFlanagan/cyclist2/pull/10#issuecomment-103955168
> >.
> >
>
>
>
> --
> Robert Flanagan
> Graduate Research Assistant
> Nuclear and Radiation Engineering Program
> Department of Mechanical Engineering
> The University of Texas at Austin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FlanFlanagan/cyclist2/pull/10#issuecomment-103956406>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Pull request merged**
