### PR TITLE
Metadata to assests

### PR DESCRIPTION
**Pull request by FlanFlanagan**

### CODE REVIEW

**Comment by scopatz** [comment]
It looks like there are merge conflicts here @FlanFlanagan.

**Comment by FlanFlanagan** [comment]
I'm getting no merge conflicts in my git terminal. I'll look into it

**Comment by scopatz** [comment]
You probably haven't pulled from `cyclus/cyclist2` recently.

**Comment by FlanFlanagan** [comment]
I pulled down metadata_to_assests using the following 

git pull https://github.com/cyclus/cyclist2.git metadata_to_assests

This should get me the most recent version of that branch right?

**Comment by scopatz** [comment]
Yes it does.  But that also makes the `metadata_to_assests` branch locally.  You likely haven't merged the `metadata_to_assests` into this `master_update` branch locally.  If you want to pull directly from another branch into your current one you have to do something like:

```
$ git pull https://github.com/cyclus/cyclist2.git metadata_to_assests:master_update
```

**Comment by FlanFlanagan** [comment]
git checkout master_update
git merge --no-ff cyclus-metadata_to_assests
git push origin master_update

This is what I do after (just like in the instructions on the PR). It's getting through the merge I can see the file changes on this branch. I'll keep trying.

**Comment by scopatz** [comment]
I mean, it might be that you are PRing from cyclus/cyclist2 -> FlanFLanagan/cyclist2.  I am not sure if this is the direction that you wanted to go.

**Comment by FlanFlanagan** [comment]
I got figured it out. And yes, that was the direction I wanted to pull

On Mon, Mar 7, 2016 at 11:19 AM, Anthony Scopatz notifications@github.com
wrote:

> I mean, it might be that you are PRing from cyclus/cyclist2 ->
> FlanFLanagan/cyclist2. I am not sure if this is the direction that you
> wanted to go.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FlanFlanagan/cyclist2/pull/20#issuecomment-193356161.

## 

Robert Flanagan Ph.D.
Post Doctoral Fellow
Department of Mechanical Engineering
University of South Carolina in Columbia

**Pull request merged**
